apiVersion: v1
kind: ConfigMap
metadata:
  name: consul-server-config
  namespace: "{{ .Values.namespace }}"
  labels:
    app: consul
    release: consul
data:
  extra-from-values.json: |-
    {
      "log_level": "DEBUG"
    }