apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.ServiceName }}
  name: {{ .Values.ServiceName }}
spec:
  clusterIP: None
  ports:
    - name: https
      port: 8501
      targetPort: https
    - name: serflan-tcp
      protocol: "TCP"
      port: 8301
      targetPort: 8301
    - name: serflan-udp
      protocol: "UDP"
      port: 8301
      targetPort: 8301
    - name: server
      port: 8300
      targetPort: 8300
    - name: dns-tcp
      protocol: "TCP"
      port: 8600
      targetPort: dns-tcp
    - name: dns-udp
      protocol: "UDP"
      port: 8600
      targetPort: dns-udp
  selector:
{{ toYaml .Values.labels | indent 4 }}
  type: ClusterIP