apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  labels: 
    verison: {{ .Values.labels }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels: 
      verison: {{ .Values.labels }}
  template:
    metadata:
      labels: 
        verison: {{ .Values.labels }}
    spec:
      containers:
      - name: helloword
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: Always
      restartPolicy: Always